### ISSUE TITLE
Frame synchronization for GoPro, Pupil Core, and Surveillance camera

### ISSUE THREAD

**Issue by Ulrich-1995** [kyotovision-public/dynamic-3d-gaze-from-afar#8]
Hello! Thank you so much for your outstanding work.
As Pupil core records a video at varying frame rates, how did you synchronize the gaze and head directions with the chest direction computed from different cameras in each frame?
To the best of my knowledge, the average fps of videos recorded by Pupil Core can be calculated, but the starting frame and ending frames are still different from the frames extracted from the videos recorded by GoPro cameras or surveillance cameras, which create videos at almost constant frame rates.

I would really appreciate your guidance.
Thank you very much

**Comment by SomaNonaka** [comment]
Thank you for your interest!

We used [SyncBac PRO](https://www.timecodesystems.com/syncbac-pro/hero6-hero7/) with [:pulse](https://www.timecodesystems.com/products-home/pulse-temp/) by Timecode Systems. These devices allow timestamps to be stored as metadata in the video recorded by each GoPro camera, and we it this for synchronizing all GoPro cameras. 
To synchronize Pupil Core and GoPro, we recorded display screen of :pulse, which shows the timestamp, with the outside camera of Pupil Core. We then manually align starting frame of Pupil Core with the timestamp. 
Because Pupil Core also stores timestamps separately by itself, we convert the format of Pupil Core's timestamps to GoPro's timestamps. We then interpolate head and gaze directions and picked up interpolated values at each GoPro's frame (timestamp) to deal with the varying frame rates of Pupil Core.

**Comment by Ulrich-1995** [comment]
Thank you very much.

Now, it is clear to me how Gopro cameras and Pupil Core are synchronized.

Did you also record the display screen of pulse with the surveillance camera for synchronization?

**Comment by SomaNonaka** [comment]
No, we didn't. We used GoPro for surveillance cameras, too.

**Comment by Ulrich-1995** [comment]
Thank you very much!
